dist: bionic
language: java

jdk:
  - openjdk11

before_install:
  - chmod +x gradlew

install: gradle wrapper --gradle-version 5.2

script:
  - "./gradlew check"

before_deploy:
  - ./gradlew clean
  - ./gradlew build
  - git config --local user.name "nwjbrandon"
  - git config --local user.email "nwjbrandon@gmail.com"
  - export NODE_OPTIONS=–max_old_space_size=8192

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_API
  file: /home/travis/build/AY1920S1-CS2113T-T09-3/main/build/libs/AlgoSenpai-0.1.0.jar
  file_glob: true
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    on_success: always
    on_failure: never
    tags: true
