= AlgoSenpai Adventures - Dev Ops
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-T09-3/main

== Build Automation

We use Gradle to automate builds of AlgoSenpai Adventures.

== Continuous Integration

We use https://travis-ci.org/[Travis CI] and https://www.appveyor.com/[AppVeyor] to perform _Continuous Integration_ on our projects.

== Coverage Reporting

We use https://coveralls.io/[Coveralls] and _Jacoco_ to track the code coverage of our projects.

== Documentation Previews

When a pull request has changes to the asciidoc files, https://www.netlify.com/[Netlify] is used to preview the HTML version
of the modified asciidoc files.

== Making a Release

Here are the steps to create a new release.

.  Update the version number in the issue tracker.
.  Generate a JAR file using Gradle by running the `gradle build` command.
.  The JAR file can then be found in the `build/libs` folder.
.  Rename the JAR file to include the version number e.g `AlgoSenpaiAdventures-v1.0`
.  Tag the repo with the version number. e.g. `v1.0`
.  https://help.github.com/articles/creating-releases/[Create a new release using GitHub] and upload the JAR file you created.

== Managing Dependencies

Gradle downloads the dependencies automatically.
