= AlgoSenpai Adventures - Documentation
:site-section: DeveloperGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:warning-caption: :warning:
endif::[]
:repoURL: https://github.com/AY1920S1-CS2113T-T09-3/main

== Introduction

We use asciidoc for writing documentation.

== Editing Documentation

You can download the AsciiDoc plugin for IntelliJ, which allows you to preview the changes you have made to your `.adoc` files in real-time.

== Editing Diagrams

We used `draw.io` to create and update the UML diagrams in the developer guide. The `.drawio` files can be found
in the `docs/diagrams` folder.

== Publishing Documentation

We publish our documentation to this website https://algosenpaiadventures.netlify.com/[AlgoSenpai Adventures]
using Netlify.

== Converting Documentation to PDF format

We use https://www.google.com/chrome/browser/desktop/[Google Chrome] for converting documentation to PDF format,
as Chrome's PDF engine preserves the hyperlinks in the documents.

Here are the steps to convert the project documentation files to PDF format.

.  Open a console and type in `gradle asciidoctor` to convert the AsciiDoc files in the `docs/` directory to HTML format.
.  Go to your generated HTML files in the `build/docs` folder, right click on them and select `Open with` -> `Google Chrome`.
.  Within Chrome, click on the `Print` option in Chrome's menu.
.  Set the destination to `Save as PDF`, then click `Save` to save a copy of the file in PDF format.
